keys:
  - &root age1lzxxtwcxvk9slq5vn2rw35gm9r93c0w0hg0wlwgn7ctu89wxpums0r8ke7
  - &laptop age17ajces2ka639rq9am5c707nz0qgqste5a25hky5mcraargryvp7s6esm7p
  - &pc age1t388ywzzej0wqmjcc87cnkhz4jwawz9p9kg6f93xkfwxx749e4psttdrl5

creation_rules:
  - path_regex: secrets/[^/]+ #.secret
    key_groups:
      - age:
          - *root
          - *laptop
          - *pc