keys:
  - &pc age1t388ywzzej0wqmjcc87cnkhz4jwawz9p9kg6f93xkfwxx749e4psttdrl5
  - &laptop age1qdslghtpq4zew5jkc6c23r9petqq3mc23xccn6hqk2qg26sx9prqdutrd3

creation_rules:
  - path_regex: secrets/[^/]+ #.secret
    key_groups:
      - age:
          - *laptop
          - *pc
